CREATE DATABASE ptumblr DEFAULT CHARACTER SET='utf8mb4';

CREATE USER 'ptumblr'@'%' IDENTIFIED BY 'chips';
GRANT ALTER,CREATE,DELETE,DROP,INDEX,INSERT,LOCK TABLES,REFERENCES,SELECT,UPDATE ON ptumblr.* TO 'ptumblr'@'%';

